### ISSUE TITLE
How to create routes file in vue js?

### ISSUE THREAD

**Issue by swati533** [jeetu-sah/vue-store#1]
Hello @jeetu-sah i want to know how to create routes files in vue js.

**Comment by jeetu-sah** [comment]
Hello @swati533 
You can check below this link for named routes.
https://jswebsolutions.in/post/how-to-define-named-route-in-vue-js

Also, check this link for Vue js routing.
https://github.com/jeetu-sah/vue-store/blob/main/src/main.js
